require 'dotenv'
fastlane_version "1.105.0"

platform :ios do
  error do |lane, exception, options|
    restore_file(path: "#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PLIST_PATH']}")
  end

  lane :setup do |options|
    produce(
      app_name: ENV['IOS_APP_NAME'],
      skip_itc: true
    )
    match(
      type: 'development'
    )
    match(
      type: ENV['IOS_EXPORT_TYPE']
    )
  end

  lane :setup_push do
    pem
  end

  lane :build do |options|
    backup_file(path: "#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PLIST_PATH']}")
    xcodeproj = "#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PROJECT_NAME']}.xcodeproj"
    xcworkspace = "#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PROJECT_NAME']}.xcworkspace"
    update_info_plist(
      xcodeproj: xcodeproj,
      display_name: ENV['IOS_APP_NAME'],
      app_identifier: ENV['IOS_APP_ID'],
      plist_path: ENV['IOS_PLIST_PATH'],
    )
    profile_env_name = "sigh_#{ENV['IOS_APP_ID']}_#{ENV['IOS_EXPORT_TYPE']}_profile-name"
    gymOptions = ({
      silent: true,
      export_method: ENV['IOS_EXPORT_TYPE'],
      xcargs: "PROVISIONING_PROFILE_SPECIFIER='#{ENV[profile_env_name]}' DEVELOPMENT_TEAM='#{ENV['IOS_TEAM_ID']}'"
    }).merge(
      File.directory?("../#{xcworkspace}") ?
        {workspace: xcworkspace} :
        {project: xcodeproj}
    )
    gym(gymOptions)
    restore_file(path: "#{ENV['IOS_PROJECT_PATH']}/#{ENV['IOS_PLIST_PATH']}")
  end

  lane :deploy_hockey do |options|
    hockey(
      notify: '0',
      ipa: ENV['IOS_IPA_PATH']
    )
  end

  lane :deploy_testflight do |options|
    pilot(
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end

  lane :deploy_staging do |options|
    Dotenv.load('.env', '.env.staging')
    setup
    build
    deploy_hockey
  end

  lane :deploy_prod do |options|
    Dotenv.load('.env', '.env.prod')
    setup
    build
    deploy_testflight
  end
end

platform :android do
  lane :build do |options|
    gradle(
      task: "assembleRelease",
      project_dir: ENV['ANDROID_PROJECT_DIR']
    )
  end

  lane :deploy_hockey do |options|
    hockey(
      notify: '0',
      apk: ENV['ANDROID_APK_PATH']
    )
  end

  lane :deploy_staging do |options|
    Dotenv.load('.env', '.env.staging')
    build
    hockey
  end

  lane :deploy_prod do |options|
    Dotenv.load('.env', '.env.prod')
    build
  end
end
