fastlane_version "1.104.0"

platform :ios do
  lane :build do |options|
    # Activate next line if you use Cocoapods
    # cocoapods(podfile: "./ios/Podfile")
    produce(skip_itc: true)
    match(type: "development")
    match()
    gym(
      configuration: "Release",
      use_legacy_build_api: true,
      silent: true
    )
  end

  lane :deploy_hockey do |options|
    build
    hockey(
      notify: '0',
      ipa: ENV['HOCKEY_IPA']
    )
  end

  lane :deploy_testflight do |options|
    build
    pilot(
      team_id: ENV['PILOT_TEAM_ID'],
      distribute_external: false,
      skip_waiting_for_build_processing: true
    )
  end
end

platform :android do
  lane :build do |options|
    gradle(task: "assembleRelease")
  end

  lane :deploy_hockey do |options|
    build
    apk_path =  "./android/app/build/outputs/apk/app-release.apk"
    hockey(
      notify: '0',
      apk: apk_path
    )
  end
end
